# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Recol.DLSSUpdater
PackageVersion: 2.7.5
PackageLocale: en-US
Publisher: Recol
PublisherUrl: https://github.com/Recol
PublisherSupportUrl: https://github.com/Recol/DLSS-Updater/issues
Author: Deco
PackageName: DLSS Updater
PackageUrl: https://github.com/Recol/DLSS-Updater
License: AGPL-3.0
LicenseUrl: https://github.com/Recol/DLSS-Updater/blob/main/LICENSE
Copyright: Copyright (c) Deco
ShortDescription: A tool to update DLSS, XeSS, and DirectStorage DLLs for various games
Description: DLSS Updater is a utility that automatically updates DLSS, XeSS, and DirectStorage DLLs for games across multiple platforms including Steam, EA Play, Ubisoft, Epic Games, GOG Galaxy, Battle.net, and Xbox Game Pass.
Moniker: dlss-updater
Tags:
- dlss
- nvidia
- gaming
- xess
- directstorage
ManifestType: defaultLocale
ManifestVersion: 1.6.0
