# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Recol.DLSSUpdater
PackageVersion: 2.7.5
PackageLocale: en-US
Publisher: Recol
PublisherUrl: https://github.com/Recol
Author: Deco
PackageName: DLSS Updater
PackageUrl: https://github.com/Recol/DLSS-Updater
License: AGPL-3.0
LicenseUrl: https://github.com/Recol/DLSS-Updater/blob/main/LICENSE
ShortDescription: A tool to update DLSS/XeSS DLLs for various games
Description: DLSS Updater is a utility that automatically updates DLSS, XeSS, and DirectStorage DLLs for games across multiple platforms.
Tags:
- dlss
- nvidia
- gaming
- xess
ManifestType: defaultLocale
ManifestVersion: 1.6.0
