PackageIdentifier: Recol.DLSSUpdater
PackageVersion: 2.7.5
MinimumOSVersion: 10.0.0.0
Platform:
- Windows.Desktop
InstallModes:
- interactive
- silent
Installers:
- Architecture: x64
  InstallerType: zip
  InstallerUrl: https://github.com/Recol/DLSS-Updater/releases/download/V2.7.5/DLSS.Updater.2.7.5.zip
  InstallerSha256: 75AE44CE02FD225333208D5F10FE7DC0E60092AD1E33A57A176320C1B77BD968
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: DLSS_Updater.exe
    PortableCommandAlias: dlss-updater
  UpgradeBehavior: install
ManifestType: installer
ManifestVersion: 1.6.0